### ISSUE TITLE
Problem in running simulation scripts

### ISSUE THREAD

**Issue by mmohaghegh** [INM-6/closed-loop-learning-in-autonomous-agents#1]
Hi,

Thank you for sharing your simulation scripts written for the corresponding paper. I am trying to run the codes on my PC, but I get an error message from gymz, which I am not able to find why this happens. I really appreciate helping me on this issue.

###############  ERROR  ###############
 

WARNING:gymz.gym_wrapper:changing environment properties
Traceback (most recent call last):
  File "/local/work/Projects/closed-loop-learning-in-autonomous-agents-master/miniconda3/envs/nest-framework/bin/gymz-controller", line 94, in <module>
    run(docopt.docopt(__doc__, version=gymz.__version__))
  File "/local/work/Projects/closed-loop-learning-in-autonomous-agents-master/miniconda3/envs/nest-framework/bin/gymz-controller", line 52, in run
    emu = gymz.GymWrapper(config)
  File "/local/work/Projects/closed-loop-learning-in-autonomous-agents-master/miniconda3/envs/nest-framework/lib/python3.6/site-packages/gymz/gym_wrapper.py", line 67, in __init__
    "entry_point": spec._entry_point,
AttributeError: 'EnvSpec' object has no attribute '_entry_point'

###############  ERROR  ###############

And a point that may help you solve this issue. I couldn't find the conda environment yml file, so I went blindly in terms of versions of the required packages.

Thank you very much in advance,

Mohammad

**Comment by jakobj** [comment]
thanks @mmohaghegh for reporting this. as you already suggested this problem most likely arises from a version mismatch of the gym package. what does `gym.__version__` return on your system?

edit: i've also created #2 which adds the missing environment file. maybe you could give that a try and let us know whether it works?

**Comment by mmohaghegh** [comment]
> thanks @mmohaghegh for reporting this. as you already suggested this problem most likely arises from a version mismatch of the gym package. what does `gym.__version__` return on your system?
> 
> edit: i've also created #2 which adds the missing environment file. maybe you could give that a try and let us know whether it works?

**Comment by mmohaghegh** [comment]
@jakobj Thanks for responding. The version is 0.15.4.

Sure, I'll try that.
Sorry, I closed the issue by mistake. Can you please open it again?

**Comment by mmohaghegh** [comment]
reopening ...

**Comment by mmohaghegh** [comment]
Thanks a lot, it worked.
